<nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
    <div class="container">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="<?= $this->url('home') ?>">
                <img src="<?= $this->basePath('img/zf-logo-mark.svg') ?>" height="28" alt="Zend Framework <?= \Application\Module::VERSION ?>"/>&nbsp;Skeleton Application
            </a>
        </div>
        <div class="collapse navbar-collapse">
            <ul class="nav navbar-nav">
            <?php 
                $navHelper = $this->navigation('navigation')->setAcl($this->acl)->setRole('guest');
                $containers = $navHelper->getContainer();
                foreach ($containers->getpages() as $page) {
                    $class = "";
                    if ($page->isActive()) {
                    	$class = "active";
                    }
                    
                    if (count($page)) {
                    	$label = $page->getLabel();
                    	$label = $this->translate($label);
                    	$label = $this->escapehtml($label);
                    	printf('<li class="dropdown %s">' . "\n", ($class ? '' . $class : ''));
                    	printf('<a href="%s" class="dropdown-toggle" data-toggle="dropdown">%s<b class="caret"></b></a>' . "\n", $page->getHref(), $label);
                    	echo '<ul class="dropdown-menu">' . "\n";
                    	
                    	foreach ($page as $subPage)
                    	{
                    	    if (!$navHelper->accept($subPage)) {
                    	    	continue;
                    	    }
                    	    printf('<li>%s</li>' . "\n", $navHelper->htmlify($subPage));
                    	}
                    	echo '</ul></li>' . "\n";
                    } else {
                        printf('<li class="%s">%s</li>' . "\n", $class, $navHelper->htmlify($page));
                    }
                }
            ?>
                				<!-- Main Navigation: Search -->
        <!--     				<form class="navbar-search pull-right"> -->
        <!--     					<input type="text" class="search-query typeahead" placeholder="Search"> -->
        <!--     				</form> -->
            				<!-- / Main Navigation: Search -->
            </ul>
        </div>
    </div>
</nav>