<?php 
$this->plugin("currencyformat")->setCurrencyCode("USD")->setLocale("en_US"); 
$this->plugin('dateFormat')->setTimezone('America/New_York')->setLocale('en_US');
?>
<div class="jumbotron">
	<h1 class="display-2">Next Steps</h1>
	<hr class="my-2">
	<p>You have successfully submitted a permit.  Below is a confirmation of your submission.  Please print out and bring with you to the Department of Public Works, with payment.</p>
	<p>If you are required to produce additional documentation required for the permit, please be sure to include those documents along with below receipt.</p>
</div>

    <div class="row">
        <div class="col-12">
            <div class="row">
                <div class="col-xs-6 col-sm-6 col-md-6">
                    <address>
                        <strong>The City of Middletown</strong>
                        <br>
                        245 deKoven Drive
                        <br>
                        Middletown, CT 06457
                        <br>
                        <abbr title="Phone">P:</abbr> 860-638-4870
                    </address>
                </div>
                <div class="col-xs-6 col-sm-6 col-md-6 text-right">
                    <p>
                        <em>Date: <?= $this->dateFormat(new DateTime($permit->CREATION_DATE), IntlDateFormatter::LONG); ?></em>
                    </p>
                    <p>
                        <em>Permit #: <?= $permit->PERMIT_NUMBER; ?></em>
                    </p>
                </div>
            </div>
            <div class="row">
                <div class="text-center">
                    <h1>Receipt of Submission</h1>
                </div>
                <table class="table table-hover">
                    <thead>
                        <tr>
                            <th>Permits</th>
                            <th class="text-center"></th>
                        </tr>
                    </thead>
                    <tbody>
                    	<?php 
                    	$aryPermits = [
                    	    'BUILDING_PERMIT',
                    	    'PLUMBING_PERMIT',
                    	    'HVAC_PERMIT',
                    	];
                    	
                    	foreach ($aryPermits as $appl_perm) {
                    	    if ($permit->$appl_perm) {
                    	        ?>
            	        <tr>
                            <td class="col-md-9"><em><?=$appl_perm;?></em></td>
                            <td class="col-md-1 text-center"></td>
                        </tr>
                    	        <?php 
                    	    }
                    	}
                    	?>
                        
                        <tr>
                            <td class="text-right">
                            <p>
                                <strong>Estimated Costs:</strong>
                            </p>
                            <p>
                                <strong>State Fee:</strong>
                            </p></td>
                            <td class="text-right">
                            <p>
                                <strong><?= $this->currencyFormat($permit->ESTIMATED_COSTS); ?></strong>
                            </p>
                            <p>
                                <strong><?= $this->currencyFormat($permit->STATE_FEE); ?></strong>
                            </p></td>
                        </tr>
                        <tr>
                            <td class="text-right"><h4><strong>Total:</strong></h4></td>
                            <td class="text-right text-danger"><h4><strong><?= $this->currencyFormat($permit->PERMIT_FEE); ?></strong></h4></td>
                        </tr>
                    </tbody>
                </table>
            </div>
        </div>
    </div>