<?php 
$this->plugin("currencyformat")->setCurrencyCode("USD")->setLocale("en_US"); 
$this->plugin('dateFormat')->setTimezone('America/New_York')->setLocale('en_US');
?>
    <div class="row">
        <div class="well col-xs-10 col-sm-10 col-md-6 col-xs-offset-1 col-sm-offset-1 col-md-offset-3">
            <div class="row">
                <div class="col-xs-6 col-sm-6 col-md-6">
                    <address>
                        <strong>The City of Middletown</strong>
                        <br>
                        245 deKoven Drive
                        <br>
                        Middletown, CT 06457
                        <br>
                        <abbr title="Phone">P:</abbr> (860) 638-4870
                    </address>
                </div>
                <div class="col-xs-6 col-sm-6 col-md-6 text-right">
                    <p>
                        <em>Date: <?= $this->dateFormat(new DateTime($permit->CREATION_DATE), IntlDateFormatter::LONG); ?></em>
                    </p>
                    <p>
                        <em>Permit #: <?= $permit->PERMIT_NUMBER; ?></em>
                    </p>
                </div>
            </div>
            <div class="row">
                <div class="text-center">
                    <h1>Receipt</h1>
                </div>
                <table class="table table-hover">
                    <thead>
                        <tr>
                            <th>Permits</th>
                            <th class="text-center"></th>
                        </tr>
                    </thead>
                    <tbody>
                        <tr>
                            <td class="col-md-9"><em>Building Permit</em></td>
                            <td class="col-md-1 text-center"></td>
                        </tr>
                        <tr>
                            <td class="text-right">
                            <p>
                                <strong>Estimated Costs:</strong>
                            </p>
                            <p>
                                <strong>State Fee:</strong>
                            </p></td>
                            <td class="text-center">
                            <p>
                                <strong><?= $this->currencyFormat($permit->ESTIMATED_COSTS); ?></strong>
                            </p>
                            <p>
                                <strong><?= $this->currencyFormat($permit->STATE_FEE); ?></strong>
                            </p></td>
                        </tr>
                        <tr>
                            <td class="text-right"><h4><strong>Total:</strong></h4></td>
                            <td class="text-center text-danger"><h4><strong><?= $this->currencyFormat($permit->PERMIT_FEE); ?></strong></h4></td>
                        </tr>
                    </tbody>
                </table>
            </div>
        </div>
    </div>