<?= $this->doctype() ?>

<html lang="en">
    <head>
        <meta charset="utf-8">
        <?= $this->headTitle('Building Permit')->setSeparator(' - ')->setAutoEscape(false) ?>

        <?= $this->headMeta()
            ->appendName('viewport', 'width=device-width, initial-scale=1.0')
            ->appendName('robots', 'noindex')
            ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
        ?>

        <!-- Le styles -->
        <?= $this->headLink(['rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/cityseal_S7Z_icon.ico'])
            ->prependStylesheet($this->basePath('css/style.css'))
            ->prependStylesheet($this->basePath('css/bootstrap-theme.min.css'))
            ->prependStylesheet($this->basePath('css/bootstrap.min.css'))
        ?>

        <!-- Scripts -->
        <?= $this->headScript()
            ->prependFile($this->basePath('js/bootstrap.min.js'))
            ->prependFile($this->basePath('js/jquery-3.1.0.min.js'))
            
            ->appendFile($this->basePath('js/accounting.min.js'))
            ->appendFile($this->basePath('js/building-permit.js'))
        ?>
    </head>
    <body>
        <?= $this->navigation('default')->menu()->setPartial('partial/navigation.phtml'); ?>
        <div class="container mt-3">
        <!-- Flash Messenger -->
            <?php echo $this->partial('partial/flashmessenger.phtml'); ?>
        	
            <?= $this->content ?>
            <hr>
            <footer>
                <p>&copy; 2017 - <?= date('Y') ?> by The City of Middletown. All rights reserved.</p>
            </footer>
        </div>
        <?= $this->inlineScript()
            ->appendFile($this->basePath('js/jquery.mask.min.js'))
        ?>
    </body>
</html>
